### ISSUE TITLE
DDL: add default value for JSON property if default provided

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/schema-guru#106]
https://github.com/json-schema/json-schema/blob/master/draft-04/schema#L44

**Comment by chuwy** [comment]
Different options for each type? ``--default-object {} --default-integer 3 ...`` ?

**Comment by alexanderdean** [comment]
No - we attach a default value to the table if a default value is asserted inside the JSON Schema...

**Comment by chuwy** [comment]
Oh. Right.

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/iglu/issues/248
