### ISSUE TITLE
Remove "Generated" timestamp from sql files

### ISSUE THREAD

**Issue by gabrielcrowdtilt** [snowplow/schema-guru#108]
For example, the beginning of an sql file generated by the tool will be like:

-- AUTO-GENERATED BY schema-ddl DO NOT EDIT
-- Generator: schema-ddl 0.1.0
-- Generated: 2015-09-10 16:28

But then, if I rerun the command over the whole directory, each time, it will change all the timestamps in all the sql files. But these files are all checked into git, so now the files have changed, when they haven't really changed. Also, if they're in git, then you have a commit history anyway and don't need a timestamp.

**Comment by chuwy** [comment]
We'll do it!
Let's call it ``--no-header`` option. For now ``schema-guru input.json | tail -n+5`` should work for you.
