### ISSUE TITLE
Update Redshift SQL table definition to use decimal or integer types

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/schema-guru#112]
If a jsonschema has field definition for a number with `multipleOf: 1` the corresponding SQL field definition should be an `integer` - currently it's a `float`.

If a jsonschema has a field definition for a number with `multipleOf: 0.01` the corresponding SQL field definition should be a decimal with the appropriate number of decimal places.

Not sure if this should be 1 ticket or 2?

**Comment by chuwy** [comment]
Duplicates snowplow/schema-ddl#42 and snowplow/schema-ddl#41

**Comment by chuwy** [comment]
This was fixed by https://github.com/snowplow/schema-guru/issues/130
