### ISSUE TITLE
Add encoding to Redshift table definitions

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/schema-guru#113]
As per Bogaert's hierarchy - thought there was a ticket to do this but can't find it - feel free to delete if I've just missed it...

cc @alexanderdean

**Comment by chuwy** [comment]
Yes it's in schema-ddl's issues snowplow/schema-ddl#29.
It will work in SG 0.4.0 release as it depends on schema-ddl 0.2.0. Current release depends on 0.1.0.

**Comment by alexanderdean** [comment]
I will try and get SG 0.4.0 out this week...
