### ISSUE TITLE
Support patternProperties?

### ISSUE THREAD

**Issue by jbrok** [snowplow/schema-guru#121]
Using Schema Guru DDL on a JSON Schema that uses `patternProperties` in 0.4.0 to create json path files and the .sql fails. The files are created but without my custom data fields from my properties. The JSON schema is created with Schema Guru (and then manually edited `patternProperties`). Schema DDL throws no error.

The documentation says this is supported:
"Object without properties, but with patternProperties becomes VARCHAR(4096)"

**JSON Schema**

```
...
  "type" : "object",
  "patternProperties" : {
    "^results(List)?$" : {
      "type" : "object",
      "properties" : {
        "subLocations" : {
...
```

**Command**
`$ ./schema-guru-0.4.0 ddl --with-json-paths ./schemas/`

**Result**
Missing data.fields.

```
-- AUTO-GENERATED BY schema-ddl DO NOT EDIT
-- Generator: schema-ddl 0.2.0
-- Generated: 2015-12-16 17:30

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.com_treatwell_results_list_1 (
    "schema_vendor"  VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_name"    VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_format"  VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_version" VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "root_id"        CHAR(36)      ENCODE RAW       NOT NULL,
    "root_tstamp"    TIMESTAMP     ENCODE LZO       NOT NULL,
    "ref_root"       VARCHAR(255)  ENCODE RUNLENGTH NOT NULL,
    "ref_tree"       VARCHAR(1500) ENCODE RUNLENGTH NOT NULL,
    "ref_parent"     VARCHAR(255)  ENCODE RUNLENGTH NOT NULL,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
```

When I change `patternProperties` back to `properties` in the JSON and regenerate the files, it's working as expected..

**Comment by chuwy** [comment]
Thanks @jbrok. Seems like a bug. I'll investigate it.

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/iglu/issues/245
