### ISSUE TITLE
Replace argot with scopt

### ISSUE THREAD

**Issue by chuwy** [snowplow/schema-guru#124]
As stated on [official website](http://software.clapper.org/argot/), project now is dead. Also it has some inconvenience for our usage.
Consider move to [scopt](https://github.com/scopt/scopt) (mature, stable, popular) or [case-app](https://github.com/alexarchambault/case-app) (simple and looks more suitable for args -> Schema context transform).

**Comment by alexanderdean** [comment]
Looks like the Argot author is recommending scopt, so happy for us to go with that...
