### ISSUE TITLE
Error in flattenJsonSchema with com.snowplowanalytics.snowplow/contexts/jsonschema/1-0-0

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/schema-guru#133]
We can't necessarily support this easily, but we should be explicit that we cannot support it in that case.

If you run this https://github.com/snowplow/iglu-central/blob/master/schemas/com.snowplowanalytics.snowplow/contexts/jsonschema/1-0-0 through Schema Guru, you get:

```
'flattenJsonSchema' - JsonSchema does not begin with an 'object' & 'properties'
```

**Comment by alexanderdean** [comment]
Pushing back as this message is coming from schema-ddl

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/iglu/issues/244
