### ISSUE TITLE
DDL: support string/number union type

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/schema-guru#136]
We should support the common scenario of:

> e.g. lots of people define a field as an integer then realize they're generating the data from e.g. ruby. and needs to be a json string rather than a json number

/cc @yalisassoon 

A string/number union type should be represented by a `VARCHAR(x)` - in other words the numeric possibility is stringly typed in the column.

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/iglu/issues/242
