### ISSUE TITLE
Placeholder for supporting migration cases 

### ISSUE THREAD

**Issue by chuwy** [snowplow/schema-guru#140]
Here I'm collecting possible Schema-migrations and ways to handle it
- New property (column) added. Addition. Will be [implemented](https://github.com/snowplow/schema-guru/issues/134) in 0.6.0. 

``` sql
ALTER TABLE ADD COLUMN ...
```
- Property become nullable. Revision. See #147

``` sql
ALTER TABLE ADD COLUMN customer_id_new string null;
INSERT INTO customer_id_new SELECT from customer_id;
ALTER TABLE DROP COLUMN customer_id;
ALTER TABLE RENAME COLUMN customer_id_new TO customer_id
END TRANSACTION;
```
- Property become union-type: `string -> [string, number]`. Revision.  See #137

**Comment by alexanderdean** [comment]
How about:

1. A default is added to a property
2. A minimum and/or maximum value is removed from a numeric

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/iglu/issues/241
