### ISSUE TITLE
Support REVISION migration for properties becoming nullable

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/schema-guru#147]
This is a revision. I want to prioritize this one from #140 to check there aren't any issues around column placement

``` sql
ALTER TABLE ADD COLUMN customer_id_new string null;
INSERT INTO customer_id_new SELECT from customer_id;
ALTER TABLE DROP COLUMN customer_id;
ALTER TABLE RENAME COLUMN customer_id_new TO customer_id
END TRANSACTION;
```

**Comment by alexanderdean** [comment]
@chuwy - this is in the wrong repo now - can you migrate over to https://github.com/snowplow/iglu please?

Could you also spend 30 mins and move over anything else which is no longer relevant?

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/iglu/issues/238
