### ISSUE TITLE
Add support for creating elasticsearch mappings

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/schema-guru#151]
Currently we don't explicitly set elasticsearch [mapping](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html) when loading data into elasticsearch from snowplow. Instead we rely on elasticsearch to infer the mapping (schema) for us.

That's a shame because we know the schema, so should be able to explicitly set mapping and avoid failures due to elasticsearch incorrectly mapping fields.

To do this we'd need schema-guru to generate elasticsearch mappings, just as it generates redshift ddls today.

**Comment by alexanderdean** [comment]
This would be awesome!

**Comment by shermozle** [comment]
Here's an example where elasticsearch gets it wrong:
`"se_value": {
                  "type": "string"
               }`

This means you can't due numeric aggregations on the structured event value.

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/iglu/issues/239
