### ISSUE TITLE
Bump schema-ddl library to 0.3.1

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/schema-guru#157]
Consider these schemas:

https://github.com/snowplow/iglu-central/tree/master/schemas/com.clearbit

Then look at these table definitions, created with 0.6.1:

https://github.com/snowplow/snowplow/pull/2635/files

Notes:

* "geo.lat" looks good
* "geo.lng" looks good
* "angellist.id" should be a INT NULL, not VARCHAR(4096)

**Comment by chuwy** [comment]
Renamed (this bug affects only integers).

**Comment by chuwy** [comment]
This is fixed in #158. But it resolves `angellist.id` and others to `INT`, not to `BIGINT` (which I guess is correct for 2147483647).

**Comment by alexanderdean** [comment]
Thanks @chuwy - I have corrected the ticket to say INT not BIGINT
