### ISSUE TITLE
Maybe update Redshift encoding for boolean fields to runlength?

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/schema-guru#169]
Have seen `analyze compression` suggest that `runlength` is better in a number of occasions. It might be worth investigating more systematically and updating schema-guru accordingly

**Comment by bogaert** [comment]
Agreed. It's the suggested choice in most cases I have seen.

**Comment by alexanderdean** [comment]
Migrate ticket to igluctl in time for R5 @chuwy ?

**Comment by chuwy** [comment]
Why not. Created ticket here: https://github.com/snowplow/iglu/issues/173
