### ISSUE TITLE
Hosted web UI down?

### ISSUE THREAD

**Issue by handrews** [snowplow/schema-guru#179]
While auditing the links on the JSON Schema implementation page for updated draft support, I noticed that http://schemaguru.snowplowanalytics.com/ (which is also linked in the readme for this repository) seems to be down.  Is the hosted web UI still a thing?

**Comment by chuwy** [comment]
Thanks for flagging @handrews. You're right it is not available right now, but we *probably* will bring it back. I think we can delete link right now and whenever it is available again I can make a new PR with updated link.

https://github.com/snowplow/snowplowanalytics.com/issues/406

**Comment by handrews** [comment]
@chuwy thanks, sounds good- I'll take it out of the list for now.  Closing this since you have it tracked elsewhere.
