### ISSUE TITLE
Add configuration options for self-describing JSON Schema

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/schema-guru#19]
Specifically:

* Vendor
* Schema name
* Version (we can default this to 1-0-0)

**Comment by alexanderdean** [comment]
This is covered by #17

**Comment by alexanderdean** [comment]
This is necessary

**Comment by chuwy** [comment]
So, it's just CLI options, right?

**Comment by alexanderdean** [comment]
Yep CLI options!
