### ISSUE TITLE
Make the assembled jarfile executable

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/schema-guru#24]
https://github.com/snowplow/snowplow/blob/release/0.9.12/3-enrich/scala-kinesis-enrich/project/BuildSettings.scala#L50

**Comment by chuwy** [comment]
Fixed by Josh https://github.com/snowplow/schema-guru/blob/master/project/BuildSettings.scala#L59

**Comment by alexanderdean** [comment]
Correct, thanks
