### ISSUE TITLE
Explore using http://www.jsonschema2pojo.org/

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/schema-guru#29]
Somehow [JSON Schema to POJO](https://github.com/joelittlejohn/jsonschema2pojo) can convert a JSON (not a schema) to a POJO, which suggests it may have logic to convert a JSON to a JSON Schema in it...

**Comment by jbeemster** [comment]
That would be cool.

**Comment by alexanderdean** [comment]
Hey @chuwy - did you look at this library? Please add your thoughts to this ticket.

**Comment by chuwy** [comment]
Couldn't see anything useful for us there. Our most important feature anyway is merge/reduce and there's nothing related to it as far as I see.
I think we can close this one.

**Comment by alexanderdean** [comment]
Agree - go ahead!
