### ISSUE TITLE
Automatic testing with ScalaCheck?

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/schema-guru#30]
This may not be possible, but the basic idea would be:

1. Generate Scala Maps at random using ScalaCheck
2. Convert those Scala Maps into JSON
3. Use schema-guru to derive the JSON Schema for the JSON
4. Validate 2 against 3 - should always validate successfully...

**Comment by alexanderdean** [comment]
ScalaCheck: https://www.scalacheck.org/

Inspired by Haskell's QuickCheck

**Comment by chuwy** [comment]
I think it isn't obligatorily to use ScalaTest for it. Taking into account that we already use specs2 as our main test runner.
Still need test cases for possible failures (validate against another schema?), thus do not close it.

**Comment by alexanderdean** [comment]
Sorry yes, this should say ScalaCheck not ScalaTest...

**Comment by alexanderdean** [comment]
Title updated
