### ISSUE TITLE
Identify and warn of misspelt properties using Levenshtein distance

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/schema-guru#31]
Suggested by @fblundun: detect fields with similar names using (measured using http://en.wikipedia.org/wiki/Levenshtein_distance), especially if they are long names.

**Comment by chuwy** [comment]
```Levenshtein(key_with_ambiguous_case, keyWithAmbiguousCase) = 6```
I think it should be special case with distance 1. What do you think, @alexanderdean ?

**Comment by alexanderdean** [comment]
I don't know much about Levenshtein! @fblundun?

**Comment by chuwy** [comment]
It is not so much about Levenshtein itself, but about how to handle keys with ambiguous cases. Because as far as I understand that is one of most common mistakes in our JSON sets.

**Comment by alexanderdean** [comment]
Ah, got it. Yes agreed!

**Comment by fblundun** [comment]
We could strip out all underscores and convert all letters to lowercase before checking the distance.

**Comment by chuwy** [comment]
What other special cases do we have beside snake_case/camelCase?

**Comment by alexanderdean** [comment]
I'll throw out some things I've seen, not saying they all need supporting:

* Removing vowels to shorten things
* Abbreviations, e.g. s versus secs, ts versus tstamp versus time versus timestamp, cat versus category, pct versus percent versus percentage
* acronyms versus full versions (e.g. page_view or pageview versus pv)
* singular versus plural

**Comment by chuwy** [comment]
At least I hope case-with-hyphens isn't something we need to be prepared for?

**Comment by alexanderdean** [comment]
Which one is case-with-hyphens?

**Comment by chuwy** [comment]
```{"this-is-a-valid-key": 42}```

**Comment by alexanderdean** [comment]
Ah! Well, if it's possible in any single JSON-producing environment, then yes it could occur :-)
