### ISSUE TITLE
Detect sensible int ranges

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/schema-guru#35]
We want to restrict to signed/unsigned, and use 2/4/8 byte ranges [1]

[1] http://docs.aws.amazon.com/redshift/latest/dg/r_Numeric_types201.html

**Comment by alexanderdean** [comment]
Example schema created manually: https://github.com/snowplow/iglu-central/blob/master/schemas/org.w3/PerformanceTiming/jsonschema/1-0-0

**Comment by chuwy** [comment]
What about zero and negative minimum?
Redshift defines negative ranges. But example schema defines minimum as 0.
We actually could detect both, but does it make any sense since Redshift don't care?

**Comment by alexanderdean** [comment]
It's a good question. Redshift is perhaps a bad example because it's constraints are informational only.

In a database like Postgres or Oracle, it's very easy to enforce a constraint such as "this field must not contain a negative number". So it feels to me like the important things are:

* Determining what int byte size is needed to hold the number
* Determining whether the number is always positive, is always negative, or can be both

Does that make sense?

**Comment by chuwy** [comment]
AFAIK, in Postgres this constraint is only about >0 and not like unsigned Int, so always positive maximum remains +32767, right?

**Comment by alexanderdean** [comment]
Hey @chuwy - I think so:

* http://stackoverflow.com/questions/20810134/why-unsigned-integer-is-not-available-in-postgresql
* http://www.postgresql.org/docs/8.1/static/ddl-constraints.html

BTW - I am sure we will end up making some tweaks to schema-guru after you've worked on a first iglu-utils release. Because iglu-utils will make the required relationships JSON Schemas<>database tables more clear...
