### ISSUE TITLE
Auto-detect enums with configurable cardinality tolerance

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/schema-guru#36]
As soon as we are regularly analyzing with lots of JSON instances, we should be able to detect enums.

We should allow a configurable cardinality to define where an enum stops being an enum and reverts back to being a simple type.

**Comment by chuwy** [comment]
@alexanderdean Do you think we need some default cardinality value? Or if it is not specified, we just not adding it?

**Comment by alexanderdean** [comment]
I think a default is difficult - if you are only processing 6 JSONs and your default is 12, then all strings will end up as enums...

**Comment by chuwy** [comment]
Ok.

**Comment by alexanderdean** [comment]
Thinking about it some more - I wonder if you have to weight cardinality by the number of JSONs you are examining.

45 discrete values in a million JSONs is an enum

6 discrete values in 12 JSONs is not an enum (or rather, not enough data points to know for sure).

**Comment by chuwy** [comment]
Well. That makes sense. If you can provide me a formula to calculate this value, I'll glad to add it.

**Comment by chuwy** [comment]
One the other hand, enum is just something we want to add or not. I think it will be better if user will decide.

**Comment by alexanderdean** [comment]
Okay - let's go for your suggestion!
