### ISSUE TITLE
Create a single-page UI in plain JS

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/schema-guru#39]
Basically swapping the panes on http://jsonschemalint.com/draft4/ :-)

1. Pane on the left to paste in the JSON instance
2. Pane on the right to paste in the JSON Schema

**Comment by alexanderdean** [comment]
Thought experiment: could we run this UI entirely browser side by embedding the schema-guru logic via scala-js?

**Comment by chuwy** [comment]
May be we could move it from far-out stuff to some near future? Because basic web UI will drastically increase it accessiblity and allow anyone to come up with new ideas and actually test it.

**Comment by chuwy** [comment]
And furthermore, I think for main purpose of this application web UI is more appropriate than CLI since it allows user to check what he wants much more deliberately and precisely.

**Comment by alexanderdean** [comment]
I think the UI is nice for quick experimentation, although the real value I think of schema-guru is when you can derive&merge from 100s of records. Still, agree, let's move it forwards...

**Comment by chuwy** [comment]
What about upload an archive? Or even drag'n'drop a bunch of files?

**Comment by alexanderdean** [comment]
Yes that could work...

**Comment by alexanderdean** [comment]
I like the idea that you could keep dragging JSONs into the left pane, one by one, and the right pane (the schema) would keep refining through merging...

**Comment by chuwy** [comment]
Actually it could be a very sophisticated app. User uploads a bunch of files, look at the schema and just presses buttons to adjust schema.
