### ISSUE TITLE
Remove format for strings where particular format appears only several times

### ISSUE THREAD

**Issue by chuwy** [snowplow/schema-guru#42]
Here, `msg`
```
[{"msg": "2010-01-01T12:00:00+01:00"}, {"msg": "not a date-time actually"}]
```
should not be recognized as format date-time.

**Comment by alexanderdean** [comment]
Agree. You want some [Mendelian inheritance](http://en.wikipedia.org/wiki/Mendelian_inheritance) for the offspring of a merge.

**Comment by alexanderdean** [comment]
This feels like a pretty core part of the merge() behavior, no? I propose including this in 0.1.0, let me know your thoughts...

**Comment by chuwy** [comment]
Yes. Defentily. But I think Mendelian inheritance here is unnecessary. It's just `{"format": "date-time"} merge {format: none} == {format: none}`. Straightforward as that.

**Comment by alexanderdean** [comment]
Sure thing!
