### ISSUE TITLE
Add Scala 2.11 support

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/schema-guru#47]
This can be a bit fiddly with the specs2 dependency - see this project for how to do it:

https://github.com/snowplow/scala-maxmind-iplookups/blob/master/project/Dependencies.scala#L50

Don't forget to update .travis too...

**Comment by chuwy** [comment]
No problems with specs2, but iglu-scala-client (unused though, so I've deleted it) blocked build since it hasn't support of 2.11.

**Comment by alexanderdean** [comment]
Thanks @chuwy - that's fine to remove iglu-scala-client...

**Comment by chuwy** [comment]
I just thought it would be useful to add same ticket to iglu-scala-client.
