### ISSUE TITLE
Add ability to segment JSON instances based on a JSON property

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/schema-guru#48]
We let users specify a JSON Path in their JSONs which tells us which JSON Schema this instance should belong to. For example, many users might have a folder full of JSON events, where the events look like this:

```json
{
    "version"    : 1,
    "type"      : "track",
    "userId"    : "019mr8mf4r",
    "event"      : "Purchased an Item",
    "properties" : {
        "revenue"        : "39.95",
        "shippingMethod" : "2-day"
    },
    "timestamp" : "2012-12-02T00:30:08.276Z"
}
```

(source https://segment.com/docs/integrations/webhooks/#track).

Then we would run schema-guru like this:

```
$ run --dir {{mixed_jsons_directory}} --output-dir /Users/guru/ --schema-by "$.event"
```

**Comment by alexanderdean** [comment]
Use this project: https://github.com/gatling/jsonpath

**Comment by chuwy** [comment]
Am I miss something? May be you mean ``"$.properties"``?

**Comment by alexanderdean** [comment]
No, it's `--schema-by "$.event"`. What this means is:

1. Read a folder of JSONs
2. Build a separate JSON Schema for each distinct value found in the `$.event` field

So one folder -> many JSON Schemas, all identified by the `$.event` field

**Comment by chuwy** [comment]
But here ``$.event`` is just a string. It's not even a valid JSON.

**Comment by alexanderdean** [comment]
Yes, so you will output a JSON Schema called `Purchased_an_Item.json` which contains all of the properties found in all supplied JSONs where `$.event == "Purchased an Item"`.

**Comment by chuwy** [comment]
Hm. Okay. Seems I got it. At least hope so.

**Comment by alexanderdean** [comment]
Okay cool - ping me if still unclear!
