### ISSUE TITLE
Submit schema-guru to http://json-schema.org/implementations.html

### ISSUE THREAD

**Issue by chuwy** [snowplow/schema-guru#50]
Also may be we could find there some more ideas to implement.

**Comment by alexanderdean** [comment]
Good idea! Let's do this as soon as 0.1.0 is out...

**Comment by chuwy** [comment]
Do you really think 0.1.0 is ready for that kind of public attention?
Btw, I think all code of 0.1.0 is already. I'm now working on blog post and README (also URL format, but that is straightforward).

**Comment by chuwy** [comment]
Also, check out http://lbovet.github.io/typson-demo/
Right pane is what I was talking about in #39.

**Comment by alexanderdean** [comment]
Okay - let's keep at 0.2.0! Almost code complete for 0.1.0 - great work @chuwy !

**Comment by alexanderdean** [comment]
This isn't strictly part of a release, so de-scheduling

**Comment by chuwy** [comment]
At last it is listed on website: http://json-schema.org/implementations.html

**Comment by alexanderdean** [comment]
Result! Nice work @chuwy
