### ISSUE TITLE
Detect field contains base64

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/schema-guru#58]
This seems like a useful one. I am always sticking base64-encoded things in JSON strings...

**Comment by chuwy** [comment]
Ok. How to annotate them?

**Comment by alexanderdean** [comment]
I guess with a string regex format: http://stackoverflow.com/questions/475074/regex-to-parse-or-validate-base64-data

**Comment by chuwy** [comment]
No, problem not with detection.
URL, IP, etc are valid values for format field. "Base64" however isn't a valid value http://json-schema.org/latest/json-schema-validation.html#anchor107

**Comment by alexanderdean** [comment]
With the pattern annotation: https://github.com/snowplow/iglu-central/blob/master/schemas/com.snowplowanalytics.snowplow/elasticsearch_enriched_event/jsonschema/1-0-1#L90

**Comment by chuwy** [comment]
Ok. Good point.

**Comment by chuwy** [comment]
Actually, string recognitions are pretty straightfoward to implement.
If we need them, we can add them in nearest release.

**Comment by alexanderdean** [comment]
Nice - let's bring this one forward then!
