### ISSUE TITLE
Auto-detect specific known enum sets

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/schema-guru#66]
E.g.:

* ISO 3166-1 alpha-2
* ISO 3166-1 alpha-3
* ISO 4217

**Comment by chuwy** [comment]
Just found out that we can easily allow user to provide his own enum sets. Is it on demand?

**Comment by chuwy** [comment]
Although user can specify custom enum sets, I think we need to built-in something besides those three. May be OSs? User Agents?

**Comment by alexanderdean** [comment]
I think let's keep it at these for 0.4.0 - keep the release batch size small...
