### ISSUE TITLE
Remove hardcoded folder paths

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/schema-guru#7]

**Comment by alexanderdean** [comment]
What does this one mean?

**Comment by chuwy** [comment]
Yep. I'd like to know too. The only one hardcoded path is BaseSchemaFile, which is 1) invalid path 2) used nowhere.

**Comment by alexanderdean** [comment]
Let's delete that var and close this ticket then?

**Comment by chuwy** [comment]
I think that val is assumed to be used for self-describing JSON. But yes, let's delete it.

**Comment by alexanderdean** [comment]
thanks
