### ISSUE TITLE
Update vagrant push to also build and publish webui artifact

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/schema-guru#72]
@chuwy - please comment on this ticket with the exact build steps required, then re-assign to Alex to complete.

**Comment by chuwy** [comment]
* zip files inside beanstalk directory
* create app as described here: http://www.incrediblemolk.com/running-a-docker-container-on-aws-elastic-beanstalk/#stalking and upload this zip archive
That's probably all we beed.

**Comment by alexanderdean** [comment]
Can you add the webgui steps too? As we discussed in Hipchat

**Comment by chuwy** [comment]
To build webui:
```bash
sbt "project schema-guru-webui" assembly 
```
This will create fatjar (as usual) and will run "gulp deploy" which will compile all JS and put it into webui/src/main/resources/web/dist directory (not tracked in git).

**Comment by alexanderdean** [comment]
Okay great, thanks

**Comment by alexanderdean** [comment]
Is the chmod +x issue on start.sh resolved?

**Comment by chuwy** [comment]
No, it isn't. I just made it executable.
So, if you just run ```zip aws.zip *``` it will be added as executable.

**Comment by alexanderdean** [comment]
Got it, thanks
