### ISSUE TITLE
CLI: don't check for .ndjson extension when --ndjson set

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/schema-guru#74]
As nobody uses the .ndjson extension really... The CLI flag should be enough.

**Comment by chuwy** [comment]
It don't checked when we parse single file.
For directories then I think we should not expect any extension like .json and just try to parse all files.

**Comment by alexanderdean** [comment]
I agree - I think with a folder, we should assume everything in it is a target

**Comment by chuwy** [comment]
Anyway, I think for Web UI .ndjson extension is the only way now to switch it to NDJSON mode.
I've encountered an interesting behavior in json4s parse function: if file contains several jsons it will parse only first, skip others and will not throw any exceptions, so we can't rely on exceptions to distinguish json/ndjson.

**Comment by alexanderdean** [comment]
I think for the web UI, a more logical approach would be to have checkboxes to reproduce the flags that are provided to the CLI. So for every CLI --flag, there would be a checkbox in the UI. Otherwise we have different behaviors which are hard to understand
