### ISSUE TITLE
Format is being misapplied

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/schema-guru#76]
I'm seeing lots of strings getting this pattern applied:

    "^([A-Za-z0-9+/]{4})*([A-Za-z0-9+/]{4}|[A-Za-z0-9+/]{3}=|[A-Za-z0-9+/]{2}==)$"

What does this signify? I am pretty sure that the properties in question are strings but shouldn't match the above format...

```json
        },
        "author": {
          "type": "string",
          "pattern": "^([A-Za-z0-9+/]{4})*([A-Za-z0-9+/]{4}|[A-Za-z0-9+/]{3}=|[A-Za-z0-9+/]{2}==)$"
        },
        "breadcrumb": {
          "type": "array",
          "items": {
            "type": "string",
            "pattern": "^([A-Za-z0-9+/]{4})*([A-Za-z0-9+/]{4}|[A-Za-z0-9+/]{3}=|[A-Za-z0-9+/]{2}==)$"
          }
        },
```

**Comment by chuwy** [comment]
This is base64 pattern, as dicussed in #58

**Comment by alexanderdean** [comment]
Hmm, interesting - I guess the trouble is that lots of short strings can be mis-identified as base64...

**Comment by chuwy** [comment]
I encountered it only once or twice. But this will be of course eliminated on any decent set of JSONs.
Also we can add length restriction, as it's not very common thing to encode short strings. Better if no pattern will be added at all.

**Comment by alexanderdean** [comment]
Length restriction is a good idea - once a field is above a certain length, if it has no spaces or punctuation then yes highly likely to be base64...

**Comment by chuwy** [comment]
Ok, then we need to decide exact length. 32?

**Comment by alexanderdean** [comment]
Let's discuss before work is started on 0.3.0

**Comment by chuwy** [comment]
I just got an idea for another option. With scalaz refactoring reduce operation will be moved out of merge and thus we can apply different reduce depending on how much instances was processed.
For example, if we processing 1-2 instances, this pattern won't be used at all. If this pattern encountered on >10 than let it be base64.

**Comment by alexanderdean** [comment]
Good idea, so let's push back to 0.4.0

**Comment by alexanderdean** [comment]
This didn't auto-close. Is it done in 0.4.0 @chuwy ?

**Comment by chuwy** [comment]
Yes, it was done. I don't know why it didn't get closed.

**Comment by alexanderdean** [comment]
No worries, closing.
