### ISSUE TITLE
Fix SchemaGuru does not create correct schema for array structures

### ISSUE THREAD

**Issue by jbeemster** [snowplow/schema-guru#81]
For structures like: `["hello"]` which is just an array with a String inside it does not create a valid JsonSchema.  It attempts to annotate the value but leaves empty arrays instead.

```json
{
  "type": "array",
  "items": {
    "type": "string",
    "format": [],
    "pattern": []
  }
}
```

**Comment by jbeemster** [comment]
I think this is due to the format and pattern reduce not happening unless it is nested inside a properties structure as per: https://github.com/snowplow/schema-guru/blob/master/src/main/scala/com.snowplowanalytics/schemaguru/generators/JsonSchemaMerger.scala#L138-L139

**Comment by alexanderdean** [comment]
@chuwy - it looks like this wasn't done in time for this release, pushing back

**Comment by alexanderdean** [comment]
Looks like this hasn't been done, @chuwy please confirm...

**Comment by alexanderdean** [comment]
I can see it in the CHANGELOG, weird...

**Comment by chuwy** [comment]
It's done too. It has no separate ticket, because it was part of refactoring. And seems I forgotten to put it in CHANGELOG. But it's done.

**Comment by alexanderdean** [comment]
Okay closing
