### ISSUE TITLE
Split project into lib, cli, webui and spark

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/schema-guru#9]

**Comment by chuwy** [comment]
What about this one?
At first glance all CLI is fully separated from all logic. I also have few TODOs in code which suggests interface to pass options from CLI and Web UI.

**Comment by alexanderdean** [comment]
I think let's push back to 0.3.0. It makes more sense to do this when we add the Spark support

**Comment by alexanderdean** [comment]
Potentially lib and cli are kept as one as the cli dependencies are trivial

**Comment by chuwy** [comment]
So, we will have another subproject schema-guru-spark?

**Comment by alexanderdean** [comment]
Yep, that will have additional dependencies which are Spark-specific...

**Comment by alexanderdean** [comment]
Pushing back...

**Comment by alexanderdean** [comment]
This was done implicitly anyway, closing
