### ISSUE TITLE
Unify CLI options

### ISSUE THREAD

**Issue by chuwy** [snowplow/schema-guru#90]
Currently we have different options with the same purpose for ``ddl`` and ``derive``.

## input
derive: ``--file`` and ``--dir`` should become a single positional parameter, for example ``schema-guru derive /path/to/json-dir``, guru itself should recognize whether it's file or dir.
ddl: already works as above, but it's not a positional parameter, it's --path option. I think it should be positional parameter.

## output
derive: now outputs by default to current dir, we can specify --output for single schema file and ``--output-dir`` for multiple schemas (doesn't create if it's not exists). As above I think it should be single option ``--output`` and guru should decide whether it's file or dir and create dir if it doesn't exists.
ddl: now we always need to specify ``--dest`` directory (doesn't create if it's not exists). I think it also should output to current dir by default, and use ``--output`` instead of ``--dest``.

Also I think it makes more sense if ``derive`` become ``schema``.

**Comment by alexanderdean** [comment]
Agree with all of that! Do we do it in 0.3.0 or 0.4.0?

**Comment by chuwy** [comment]
I think it would be better for 0.3.0 so we won't introduce incompatible API on every version (we already introducing it in 0.3.0 with subcommands).

**Comment by alexanderdean** [comment]
Agree - sounds v sensible
